@echo off

for /f "tokens=1,2 delims==" %%i in (app_version) do set %%i=%%j

call git_version.bat

echo app_version: %MAJOR_VERSION%.%MINOR_VERSION%.%PATCH_VERSION%.%GIT_VERSION_COMMIT%(%GIT_VERSION%)


set assemblyinfo_file_location=.\IpPortEndpointCheck\Properties\AssemblyInfo.cs


echo /* DO NOT EDIT. This file (and "version") is generated by generate_version.bat. */ >%assemblyinfo_file_location% 2>&1
echo using System.Reflection; >>%assemblyinfo_file_location%  2>&1 
echo using System.Runtime.CompilerServices; >>%assemblyinfo_file_location%  2>&1 
echo using System.Runtime.InteropServices; >>%assemblyinfo_file_location%  2>&1 

echo [assembly: AssemblyTitle("Find Open Port")] >>%assemblyinfo_file_location%  2>&1 
echo [assembly: AssemblyDescription("A tiny tool to check whether tcp or udp port opened.")] >>%assemblyinfo_file_location%  2>&1 
echo [assembly: AssemblyConfiguration("")] >>%assemblyinfo_file_location%  2>&1 
echo [assembly: AssemblyCompany("")] >>%assemblyinfo_file_location%  2>&1 
echo [assembly: AssemblyProduct("Find Open Port")] >>%assemblyinfo_file_location%  2>&1 
echo [assembly: AssemblyCopyright("Copyright (C) wangyoucao577@gmail.com 2016")] >>%assemblyinfo_file_location%  2>&1 
echo [assembly: AssemblyTrademark("")] >>%assemblyinfo_file_location%  2>&1 
echo [assembly: AssemblyCulture("")] >>%assemblyinfo_file_location%  2>&1 

echo [assembly: ComVisible(false)] >>%assemblyinfo_file_location%  2>&1 

echo [assembly: Guid("c039aa09-0d13-48cf-a826-e0162240b1f9")] >>%assemblyinfo_file_location%  2>&1 
echo [assembly: AssemblyVersion("%MAJOR_VERSION%.%MINOR_VERSION%.%PATCH_VERSION%.%GIT_VERSION_COMMIT%")] >>%assemblyinfo_file_location%  2>&1 
echo [assembly: AssemblyFileVersion("%MAJOR_VERSION%.%MINOR_VERSION%.%PATCH_VERSION%.%GIT_VERSION_COMMIT%(%GIT_VERSION%)")] >>%assemblyinfo_file_location%  2>&1 

echo "Generate version done!"
